<?php

use Illuminate\Database\Seeder;

class PRsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('prs')->insert([
            [
                'CardID' => 19,
                'PRName' => '鳴沢氷穴',
                'PRPhotoPath' => 'Chubu/Yamanashi/narusawahyouketsu.png',
                'PRDescription' => '山梨県南都留郡鳴沢村に立地する総延長156メートル、幅1.5-11メートル、高さ1-3.6メートルの溶岩洞。',
                'latitude' => 35.490101,
                'longitude' => 138.721161,
            ],
            [
               'CardID' => 19,
               'PRName' => '河口湖',
               'PRPhotoPath' => 'Chubu/Yamanashi/kawaguchiko.png',
               'PRDescription' => '富士五湖の1つに数えられる相模川水系の湖である。富士箱根伊豆国立公園に指定されている。',
               'latitude' => 35.50053,
               'longitude' => 138.761353,
            ],
           [
               'CardID' => 19,
               'PRName' => '忍野八海',
               'PRPhotoPath' => 'Chubu/Yamanashi/osinohakkai.png',
               'PRDescription' => '山梨県南都留郡忍野村にある湧泉群。国指定の天然記念物、名水百選に指定。県の新富嶽百景にも選定されている。',
               'latitude' => 35.457275,
               'longitude' => 138.833191,
           ],
           [
               'CardID' => 20,
               'PRName' => '歴史の宿金具屋',
               'PRPhotoPath' => 'Chubu/Nagano/kanaguya.png',
               'PRDescription' => '長野電鉄山ノ内線湯田中駅から車で約10分のところに位置する旅館。昭和初期に建てられた歴史ある建物で2棟は国の登録文化財に認定されている。',
               'latitude' => 36.735012,
               'longitude' => 138.477127,
           ],
           [
               'CardID' => 20,
               'PRName' => '中山道妻籠宿',
               'PRPhotoPath' => 'Chubu/Nagano/tsumagojyuku.png',
               'PRDescription' => '江戸時代の宿場町の面影を色濃く残す日本初の重要伝統的建造物群保存地区。1968年、全国に先駆けて町並み保存をはじめ、1976年に国の「重要伝統的建造物群保存地区」に第1号として選定された。',
               'latitude' => 35.575153,
               'longitude' => 137.62149,
           ],
           [
               'CardID' => 21,
               'PRName' => '郡上八幡城',
               'PRPhotoPath' => 'Chubu/Gifu/ginjyouhchimanjyou.png',
               'PRDescription' => '天守閣は再建80周年を迎えた、日本最古の木造再建城。',
               'latitude' => 35.753132,
               'longitude' => 136.957611,
           ],
           [
               'CardID' => 22,
               'PRName' => '浄蓮の滝',
               'PRPhotoPath' => 'Chubu/Shizuoka/jyorennotaki.png',
               'PRDescription' => '狩野川上流にかかる伊豆を代表する名瀑布. 浄蓮の滝. 深い樹木が生い茂る中、玄武岩の崖に高さ25m、幅7mの滝がかかっている。',
               'latitude' => 34.882061,
               'longitude' => 138.929047,
           ],
           [
               'CardID' => 22,
               'PRName' => '田貫湖',
               'PRPhotoPath' => 'Chubu/Shizuoka/tanukiko.png',
               'PRDescription' => '静岡県富士宮市にある湖。朝霧高原にあり、周囲4Kmの人口湖である。逆さ富士・ダイヤモンド富士などの富士山ビュースポットとして人気。',
               'latitude' => 35.367393,
               'longitude' => 138.567856,
           ],
           [
               'CardID' => 22,
               'PRName' => '堂ヶ島天窓洞',
               'PRPhotoPath' => 'Chubu/Shizuoka/dougasimatensoudou.png',
               'PRDescription' => '昭和10年に天然記念物に指定された、凝灰岩でできている海触洞くつ。遊覧船のほか、堂ヶ島遊歩道のコースでは、天窓洞を上から見おろすこともできる。',
               'latitude' => 34.77541,
               'longitude' => 138.775635,
           ],
           [
               'CardID' => 22,
               'PRName' => 'ヒリゾ浜',
               'PRPhotoPath' => 'Chubu/Shizuoka/hirizohama.png',
               'PRDescription' => 'ヒリゾ浜は南伊豆の最南端、石廊崎と中木の境にある海岸です。国立公園に指定されている半島の先端に位置し、切り立った崖に覆われているため、渡り船でしか行くことができません。そのため、手付かずの自然が残る南伊豆の秘境と呼ばれている。',
               'latitude' => 34.617287,
               'longitude' => 138.824142,
           ],
           [
               'CardID' => 22,
               'PRName' => '龍宮公園 (竜宮窟)',
               'PRPhotoPath' => 'Chubu/Shizuoka/ryugukutsu.png',
               'PRDescription' => 'ジオサイトとして認定された、直径約50メートル程の天窓が開く神秘的な洞窟。',
               'latitude' => 34.644127,
               'longitude' => 138.910675,
           ],
           [
               'CardID' => 23,
               'PRName' => '犬山城',
               'PRPhotoPath' => 'Chubu/Aichi/inuyamajyou.jpg',
               'PRDescription' => '犬山城は、室町時代の天文6年（1537）に建てられ、天守は現存する日本最古の様式で織田信長の叔父にあたる織田信康が築いたと言われている。',
               'latitude' => 35.387585,
               'longitude' => 136.938782,
           ],
           [
               'CardID' => 24,
               'PRName' => '伊勢神宮',
               'PRPhotoPath' => 'Kinki/Mie/isejinngu.png',
               'PRDescription' => '内宮・外宮をはじめ、125の宮社からなる神宮。',
               'latitude' => 36.245651,
               'longitude' => 136.129059,
           ],
           [
               'CardID' => 25,
               'PRName' => '琵琶湖疏水',
               'PRPhotoPath' => 'Kinki/Mie/biwakososui.png',
               'PRDescription' => '琵琶湖の湖水を西隣の京都市へ流すため、明治時代に作られた水路である。国の史跡に指定されている。',
               'latitude' => 35.009968,
               'longitude' => 135.857178,
           ],
           [
               'CardID' => 26,
               'PRName' => '東寺',
               'PRPhotoPath' => 'Kinki/Kyoto/touji.png',
               'PRDescription' => '平安遷都の時に羅城門の東西に建立された東西官寺の一つ。五重塔(国宝)は徳川家光が再建、日本一の高さ。',
               'latitude' => 34.981094,
               'longitude' => 135.747742,
           ],
           [
               'CardID' => 26,
               'PRName' => '平等院',
               'PRPhotoPath' => 'Kinki/Kyoto/byoudouin.png',
               'PRDescription' => '平安時代後期・11世紀の建築、仏像、絵画、庭園等を今日に伝え、「古都京都の文化財」として世界遺産に登録されている。',
               'latitude' => 34.889397,
               'longitude' => 135.807358,
           ],
           [
               'CardID' => 26,
               'PRName' => '永観堂禅林寺',
               'PRPhotoPath' => 'Kinki/Kyoto/zenrinji.png',
               'PRDescription' => '紅葉の名所として知られ、古くより「秋はもみじの永観堂」といわれる。',
               'latitude' => 35.013931,
               'longitude' => 135.795181,
           ],
           [
               'CardID' => 26,
               'PRName' => '東福寺',
               'PRPhotoPath' => 'Kinki/Kyoto/touhukuji.png',
               'PRDescription' => '宋国原産の三葉楓が特徴の東福寺の紅葉は、黄金色に輝く景観から「秋のすえ」「洛陽の奇観」の別称でも親しまれている。',
               'latitude' => 34.974686,
               'longitude' => 135.771835,
           ],
           [
               'CardID' => 26,
               'PRName' => '祇王寺',
               'PRPhotoPath' => 'Kinki/Kyoto/gioji.png',
               'PRDescription' => '京都奥嵯峨「平家物語」悲恋の尼寺として知られる。',
               'latitude' => 35.010399,
               'longitude' => 135.716476,
           ],
           [
               'CardID' => 26,
               'PRName' => '天龍寺',
               'PRPhotoPath' => 'Kinki/Kyoto/tenryuji.png',
               'PRDescription' => '足利尊氏が後醍醐天皇の菩提を弔うために建立し、四季折々の表情を見せることで、人気がある。',
               'latitude' => 35.016335,
               'longitude' => 135.674423,
           ],
           [
               'CardID' => 27,
               'PRName' => '大阪城',
               'PRPhotoPath' => 'Kinki/Osaka/osakajou.jpg',
               'PRDescription' => '安土桃山時代に摂津国東成郡生玉荘大坂に築かれ、江戸時代に修築された日本の城。国の特別史跡に指定されている。',
               'latitude' => 34.686817,
               'longitude' => 135.526001,
           ],
           [
               'CardID' => 28,
               'PRName' => '姫路城',
               'PRPhotoPath' => 'Kinki/Hyogo/himejijyou.png',
               'PRDescription' => '姫路を象徴する美しい城。1613 年頃の完成。白い城壁、連立式天守、堀、廊下、桜が有名。',
               'latitude' => 34.843143,
               'longitude' => 134.693542,
           ],
           [
               'CardID' => 29,
               'PRName' => '東大寺',
               'PRPhotoPath' => 'Kinki/Nara/todaiji.png',
               'PRDescription' => '大仏さまで知られる奈良時代の代表的な寺院で大仏殿は世界最大級の木造建築物',
               'latitude' => 34.691601,
               'longitude' => 135.839737,
           ],
           [
               'CardID' => 29,
               'PRName' => '谷瀬の吊り橋',
               'PRPhotoPath' => 'Kinki/Nara/tanizenotsuribashii.png',
               'PRDescription' => '熊野川（十津川）に架る、長さ297m、川面からの高さ54mの日本有数の長さを誇る鉄線のつり橋。',
               'latitude' => 34.107666,
               'longitude' => 135.755722,
           ],
           [
               'CardID' => 30,
               'PRName' => '高野山 奥之院',
               'PRPhotoPath' => 'Kinki/Wakayama/okunoin.png',
               'PRDescription' => '高野山を開いた弘法大師空海が入定した場所に御廟があり、神聖な場所とされている。',
               'latitude' => 34.219963,
               'longitude' => 135.598831,
           ],
           [
               'CardID' => 31,
               'PRName' => '水木しげるロード',
               'PRPhotoPath' => 'Chugoku/Tottori/sigeru.jpg',
               'PRDescription' => '水木しげるロードは、日本の鳥取県境港市にある商店街の名称。観光対応型商店街 であり、漫画家・水木しげるが描く妖怪の世界観をテーマとした観光名所として日本では 広く知られている。',
               'latitude' => 35.545429,
               'longitude' => 133.22551,
           ],
           [
               'CardID' => 32,
               'PRName' => '松江城',
               'PRPhotoPath' => 'Chugoku/Shimane/matsuejyou.png',
               'PRDescription' => '松江城は、全国で現存する12天守のうちのひとつで、“国宝”です。唯一の正統天守閣ともいわれている。',
               'latitude' => 35.476288,
               'longitude' => 133.050095,
           ],
           [
               'CardID' => 32,
               'PRName' => '宍道湖',
               'PRPhotoPath' => 'Chugoku/Shimane/sinjiko.png',
               'PRDescription' => '宍道湖は全国で7番目、中海は全国で5番目に大きな湖。',
               'latitude' => 35.449474,
               'longitude' => 132.856903,
           ],
           [
               'CardID' => 33,
               'PRName' => '岡山城',
               'PRPhotoPath' => 'Chugoku/Okayama/okayamajyo.png',
               'PRDescription' => '戦国時代に、備前東部から興って、美作、備中東部まで勢力を伸ばした宇喜多氏が本拠としたことで近世城郭の基礎が生まれ、その後小早川氏、池田氏により整備、拡張が行われた。',
               'latitude' => 34.66468,
               'longitude' => 133.93634,
           ],
           [
               'CardID' => 34,
               'PRName' => '広島平和記念資料館',
               'PRPhotoPath' => 'Chugoku/Hiroshima/hiroshimaheiwakinenkan.png',
               'PRDescription' => '1945 年に広島が経験した原爆投下に関する書類や資料が展示されている。',
               'latitude' => 34.39502,
               'longitude' => 132.451599,
           ],
            [
                'CardID' => 34,
                'PRName' => '宮島 (厳島)',
                'PRPhotoPath' => 'Chugoku/Hiroshima/itsukushima.png',
                'PRDescription' => '西日本の広島湾に浮かぶ小さな島で、森林や古い神社仏閣で知られている。沖合に立つ壮大な朱色の大鳥居へは、干潮時になると歩いて渡れる。',
                'latitude' => 34.303787,
                'longitude' => 132.326599,
            ],
            [
                'CardID' => 35,
                'PRName' => '秋芳洞',
                'PRPhotoPath' => 'Chugoku/Yamaguchi/akiyoshidou.png',
                'PRDescription' => '秋吉台国定公園の地下100m、その南麓に開口する日本屈指の大鍾乳洞',
                'latitude' => 34.214283,
                'longitude' => 131.32843,
            ],
            [
                'CardID' => 35,
                'PRName' => '角島大橋',
                'PRPhotoPath' => 'Chugoku/Yamaguchi/tsunoshimaoohashi.png',
                'PRDescription' => '約1.8kmの長さで本州と離島・角島を結ぶ日本屈指の長さを誇る離島架橋',
                'latitude' => 33.957279,
                'longitude' => 130.940994,
            ],
            [
                'CardID' => 36,
                'PRName' => '奥祖谷二重かずら橋',
                'PRPhotoPath' => 'Shikoku/Tokushima/kazurabashi.png',
                'PRDescription' => '平家一族が、平家の馬場に通うために架けたといわれる橋。',
                'latitude' => 33.872398,
                'longitude' => 133.988571,
            ],
            [
                'CardID' => 37,
                'PRName' => '栗林公園',
                'PRPhotoPath' => 'Shikoku/Kagawa/ritsurinpark.png',
                'PRDescription' => '江戸時代初期の姿を今に残す回遊式大名庭園で、国の特別名勝に指定されている庭園の中でも最大の広さを誇る。四季折々の美しさを醸し出す庭園美が魅力',
                'latitude' => 34.329414,
                'longitude' => 134.044235,
            ],
            [
                'CardID' => 38,
                'PRName' => '松山城',
                'PRPhotoPath' => 'Shikoku/Ehime/matuyamajou.png',
                'PRDescription' => '現存十二天守のなかで唯一、親藩・松平家によって建築された広大な城。21棟の国の重要文化財を有し、城郭建築としての見どころが満載です。',
                'latitude' => 33.845367,
                'longitude' => 132.764404,
            ],
            [
                'CardID' => 38,
                'PRName' => '亀老山展望公園',
                'PRPhotoPath' => 'Shikoku/Ehime/kirousantenboupark.png',
                'PRDescription' => '来島海峡大橋を上から眺められるしまなみ海道随一の絶景ポイント。',
                'latitude' => 34.06636,
                'longitude' => 132.997604,
            ],
            [
                'CardID' => 39,
                'PRName' => '龍河洞',
                'PRPhotoPath' => 'Shikoku/Kochi/ryukadou.jpg',
                'PRDescription' => '日本三大鍾乳洞の1つに数えられ、1934年に日本政府によって、国の天然記念物および国の史跡に指定されている。',
                'latitude' => 33.602039,
                'longitude' => 133.737778,
            ],
            [
                'CardID' => 40,
                'PRName' => '福岡城',
                'PRPhotoPath' => 'Kyushu/Fukuoka/hukuokajyou.png',
                'PRDescription' => '現在の福岡県福岡市中央区に築かれた江戸時代の日本の城。別名、舞鶴城、石城。国の史跡に指定されている。',
                'latitude' => 33.583244,
                'longitude' => 130.381927,
            ],
            [
                'CardID' => 40,
                'PRName' => '白糸の滝',
                'PRPhotoPath' => 'Kyushu/Fukuoka/shiraitonotaki.png',
                'PRDescription' => '糸島市の南側、羽金山の中腹530mに位置する白糸の滝',
                'latitude' => 33.477493,
                'longitude' => 130.180237,
            ],
            [
                'CardID' => 40,
                'PRName' => '光明禅寺',
                'PRPhotoPath' => 'Kyushu/Fukuoka/koumyouzenji.png',
                'PRDescription' => '苔寺の名で親しまれているように苔の美しい庭があるお寺。',
                'latitude' => 33.516403,
                'longitude' => 130.534576,
            ],
            [
                'CardID' => 41,
                'PRName' => '吉野ヶ里遺跡',
                'PRPhotoPath' => 'Kyushu/Saga/yoshinogari-iseki.png',
                'PRDescription' => 'およそ50ヘクタールにわたって残る弥生時代の大規模な環濠集落跡で知られる。',
                'latitude' => 33.321167,
                'longitude' => 130.388885,
            ],
            [
                'CardID' => 41,
                'PRName' => '祐徳稲荷神社',
                'PRPhotoPath' => 'Kyushu/Saga/yutokuinari.png',
                'PRDescription' => '別名鎮西日光。 伏見稲荷大社、笠間稲荷神社とともに日本三大稲荷の一つに数えられる。',
                'latitude' => 33.075928,
                'longitude' => 130.106949,
            ],
            [
                'CardID' => 41,
                'PRName' => '唐津城',
                'PRPhotoPath' => 'Kyushu/Saga/karatujyo.png',
                'PRDescription' => '満島山を中心に鶴が翼を広げたように見えることから舞鶴城とも呼ばれる。',
                'latitude' => 33.453754,
                'longitude' => 129.978348,
            ],
            [
                'CardID' => 42,
                'PRName' => 'ハウステンボス',
                'PRPhotoPath' => 'Kyushu/Nagasaki/Housetenbosu.png',
                'PRDescription' => 'オランダの街並みを再現し、テーマはヨーロッパ全体である。東京ディズニーリゾートの1.5倍の敷地面積で、単独テーマパークとして日本最大である。',
                'latitude' => 33.086971,
                'longitude' => 129.791412,
            ],
            [
                'CardID' => 42,
                'PRName' => '端島',
                'PRPhotoPath' => 'Kyushu/Nagasaki/hasima.png',
                'PRDescription' => '明治時代から昭和時代にかけて海底炭鉱によって栄え、東京以上の人口密度を有していた。軍艦島の通称で知られている。',
                'latitude' => 32.657421,
                'longitude' => 129.753342,
            ],
            [
                'CardID' => 42,
                'PRName' => 'グラバー園',
                'PRPhotoPath' => 'Kyushu/Nagasaki/gura-ba-en.png',
                'PRDescription' => 'イギリス人商人グラバー、リンガー、オルトの旧邸があった敷地に、長崎市内に残っていた歴史的建造物を移築し、野外博物館の状態を呈している。',
                'latitude' => 32.733505,
                'longitude' => 129.868912,
            ],
            [
                'CardID' => 43,
                'PRName' => '熊本城',
                'PRPhotoPath' => 'Kyushu/Kumamoto/kumamotojyo.png',
                'PRDescription' => '安土桃山時代から江戸時代の日本の城。別名「銀杏城」。 加藤清正が中世城郭を取り込み改築した平山城で、加藤氏改易後の江戸時代の大半は熊本藩細川家の居城。',
                'latitude' => 32.805367,
                'longitude' => 130.705841,
            ],
            [
                'CardID' => 43,
                'PRName' => '阿蘇山',
                'PRPhotoPath' => 'Kyushu/Kumamoto/asozan.png',
                'PRDescription' => '日本の九州中央部、熊本県阿蘇地方に位置する活火山。 2007年、日本の地質百選に「阿蘇」として選定された。',
                'latitude' => 32.931725,
                'longitude' => 131.075363,
            ],
            [
                'CardID' => 43,
                'PRName' => '阿蘇ファームランド',
                'PRPhotoPath' => 'Kyushu/Kumamoto/fa-murnd.png',
                'PRDescription' => '熊本県阿蘇郡南阿蘇村にある公園。園内には、癒・泊・動・栽・食・買の6つのテーマに分けた施設がある。',
                'latitude' => 32.849823,
                'longitude' => 131.024704,
            ],
            [
                'CardID' => 44,
                'PRName' => '別府温泉',
                'PRPhotoPath' => 'Kyushu/Oita/beppuonsen.png',
                'PRDescription' => '大分県別府市の市内各地に数百ある温泉の総称。別府八湯、別府温泉郷とも呼ばれる。温泉都市として知られる別府は、源泉数、湧出量ともに日本一。',
                'latitude' => 33.277599,
                'longitude' => 131.50592,
            ],
            [
                'CardID' => 44,
                'PRName' => '金鱗湖',
                'PRPhotoPath' => 'Kyushu/Oita/kinrinko.png',
                'PRDescription' => '大分川の源流のひとつであり、この池に朝霧がかかる風景は由布院温泉を代表する景観となっている。',
                'latitude' => 33.264503,
                'longitude' => 131.355728,
            ],
            [
                'CardID' => 44,
                'PRName' => '別府地獄めぐり',
                'PRPhotoPath' => 'Kyushu/Oita/beppujigoku.png',
                'PRDescription' => '大分県別府市の別府温泉に多数存在する様々な奇観を呈する自然湧出の源泉「地獄」を、定期観光バスなどで周遊する定番の観光コースである。',
                'latitude' => 33.31826,
                'longitude' => 131.470016,
            ],
            [
                'CardID' => 45,
                'PRName' => '照葉大吊橋',
                'PRPhotoPath' => 'Kyushu/Miyazaki/teruhaootsurubashi.png',
                'PRDescription' => '照葉樹林地帯に架かる水面からの高さ142m、長さ250m、幅1mの吊橋で、歩道吊橋としては世界最大級。',
                'latitude' => 31.997738,
                'longitude' => 131.257141,
            ],
            [
                'CardID' => 46,
                'PRName' => '白谷雲水峡',
                'PRPhotoPath' => 'Kyushu/Kagoshima/shirataniunshuikyou.png',
                'PRDescription' => '標高600～1,300メートル、面積424ヘクタールにわたって広がる照葉樹林からヤクスギ林に至る森林。',
                'latitude' => 30.397631,
                'longitude' => 130.640228,
            ],
            [
                'CardID' => 47,
                'PRName' => 'ガンガラーの谷',
                'PRPhotoPath' => 'Kyushu/Okinawa/gangara-notani.png',
                'PRDescription' => '数十万年前までは鍾乳洞だった場所が崩れてできた、手つかずの自然が残る亜熱帯の森。',
                'latitude' => 26.144604,
                'longitude' => 127.744347,
            ],
        ]);
    }
}
